- hosts: localhost
  gather_facts: false
  tasks:
    - name: Uninstall Helm release
      ansible.builtin.command:
        cmd: helm uninstall crm -n crm
      failed_when: false

    - name: Delete cloudflared
      ansible.builtin.command:
        cmd: kubectl delete -n crm deploy cloudflared secret cloudflared-token
      failed_when: false

    - name: (optional) Keep PV for data safety; delete PVC only
      ansible.builtin.command:
        cmd: kubectl -n crm delete pvc crm-mysql-pvc
      failed_when: false
