- hosts: localhost
  gather_facts: false
  tasks:
    - name: Create namespace + PV/PVC
      ansible.builtin.command:
        cmd: kubectl apply -f k8s/pv-nfs.yaml

    - name: Create cloudflared token secret (reads env CLOUDFLARED_TOKEN)
      ansible.builtin.command:
        cmd: >
          kubectl -n crm create secret generic cloudflared-token
          --from-literal=TUNNEL_TOKEN="${CLOUDFLARED_TOKEN}"
      environment:
        CLOUDFLARED_TOKEN: "{{ lookup('env','CLOUDFLARED_TOKEN') }}"
      register: secret_out
      failed_when: false   # ignore if already exists

    - name: Deploy cloudflared
      ansible.builtin.command:
        cmd: kubectl apply -f k8s/cloudflared-deploy.yaml

    - name: Install/upgrade Helm chart
      ansible.builtin.command:
        cmd: helm upgrade --install crm ./crm-chart -n crm
